server:
  port: 8090
  application:
     name: demoservice

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_NUMBERS_FOR_ENUMS: true
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
      FAIL_ON_UNKNOWN_PROPERTIES: true
  jpa:
     properties:
       hibernate:
         jdbc:
           time_zone: UTC
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties.hibernate.jdbc.time_zone : UTC
#    show-sql: true
#    hibernate:
#       ddl-auto: validate
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
     url: ${datasource.url}
     username: ${datasource.username}
     password: ${datasource.password}
     driverClassName: com.mysql.cj.jdbc.Driver


mail:
   username: macrologwebapp@gmail.com
   password: ${mailpassword}
   host: smtp.gmail.com
   port: 587

---
spring:
  profiles: arjan

  datasource:
#     url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&serverTimezone=UTC
     url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&serverTimezone=CET
     username: arjan
     password: fhjfgj!3ADD

mail:
   username: doethetniet@gmail.com
   password: 'doethetniet'
---
spring:
  profiles: carmen

  datasource:
     url: jdbc:mysql://localhost:3306/macrolog_dev?autoReconnect=true&useSSL=false&serverTimezone=CET
     username: macrolog
     password: Macrolog01

mail:
   username: doethetniet@gmail.com
   password: 'doethetniet'


---
spring:
  profiles: test
  datasource:
     url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
     username: sa
     password: sa
     driverClassName: org.h2.Driver


  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

hibernate.jdbc.timeZone: UTC

mail:
   username: doethetnietp@gmail.com
   password: 'doethetniet'

#logging:
#  level:
#    org:
#      hibernate:
#        sql: INFO
#        type.descriptor.sql.BasicBinder: TRACE



